engines:
  rubocop:
    enabled: true
exclude_paths:
- 'vendor/**/*'
- 'tmp/**/*'
- 'lib/procedo/formula/language.rb'
- 'lib/working_set/query_language.rb'
- 'db/schema.rb'
- 'bin/spring'
- 'bin/rails'
- 'bin/rake'
        